// <auto-generated />
namespace Nhom8_Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ChiTietDonHang : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ChiTietDonHang));
        
        string IMigrationMetadata.Id
        {
            get { return "202312131901105_ChiTietDonHang"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
