// <auto-generated />
namespace Nhom8_Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class LoaiSanPham : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LoaiSanPham));
        
        string IMigrationMetadata.Id
        {
            get { return "202312131836367_LoaiSanPham"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
